### ISSUE TITLE
Middleware support?

### ISSUE THREAD

**Issue by matthewmueller** [jaschaephraim/lrserver#12]
Hey thanks for creating this :-)

I was wondering if it makes sense in the scope of this project for the livereload server to implement an `http.Handler` interface?

It would allow less port binding and would be a bit easier to integrate into existing dev servers.

**Comment by jaschaephraim** [comment]
@matthewmueller Great idea. I'll update in the next week or so.

**Comment by jaschaephraim** [comment]
Well I'm only a year late, but I had a chance to take another look at this and decided this feature would be beyond the scope of the project. I'll maintain this repo as a simple, solid, standalone server, but probably won't be adding any features in the future.

**Comment by matthewmueller** [comment]
Haha fair enough! Funnily enough, I looked at this again last week and created a version that does implement it as middleware. It's heavily influenced by your work, so thanks for that!

 I need to clean it up, but I'll post a link here once it's public to let others choose.

**Comment by jaschaephraim** [comment]
Awesome! Yes please keep me posted, I'll be sure to link to your project in the readme.

**Comment by ryanerwin** [comment]
@matthewmueller  would be awesome if you've got a live reload implementation that you are ready to post long with the lrserver one!

**Comment by matthewmueller** [comment]
Haha, the thread that keeps getting forgotten and revived 😁

Here's the code: [go-livereload-master.zip](https://github.com/jaschaephraim/lrserver/files/5141340/go-livereload-master.zip)

It is working. It's just untested and undocumented. Example usage:

```go
middleware := livereload.Watch("*.js")
router := some.Router()
handler := middleware(router)
http.ListenAndServe(":9000", handler)
```

Sorry for the bare minimum. I didn't make progress since the last message and I probably won't for the foreseeable future. Maybe this is better than nothing? 🤷‍♂️
